// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Todo_Assignment.API.Data.DbContexts;

#nullable disable

namespace Todo_Assignment.API.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Todo_Assignment.API.Data.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LatestUpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Urgent",
                            CreatedDateTime = new DateTime(2023, 3, 12, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9184),
                            Description = "Completing the first task is a big leap of success.",
                            DueDate = new DateTime(2023, 6, 23, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9176),
                            IsDeleted = false,
                            LatestUpdatedDateTime = new DateTime(2023, 3, 15, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9186),
                            Title = "First Task"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Assignment",
                            CreatedDateTime = new DateTime(2023, 3, 15, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9238),
                            Description = "Create a new To-Do using Angular and ASP.NET for API.",
                            DueDate = new DateTime(2023, 3, 23, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9237),
                            IsDeleted = false,
                            LatestUpdatedDateTime = new DateTime(2023, 3, 15, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9238),
                            Title = "To-Do List Project"
                        },
                        new
                        {
                            Id = 3,
                            Category = "OnBoarding",
                            CreatedDateTime = new DateTime(2023, 4, 14, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9254),
                            Description = "OnBoarding Sessions for AIP interns with HR and Mentors",
                            DueDate = new DateTime(2023, 3, 29, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9253),
                            IsDeleted = true,
                            LatestUpdatedDateTime = new DateTime(2023, 4, 5, 2, 22, 58, 218, DateTimeKind.Utc).AddTicks(9254),
                            Title = "OnBoarding Session #1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
